#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))


def render(summary: dict) -> str:
    lines = [
        "# 80286 Real-Mode Verification Table",
        "",
        "Generated by `scripts/build_80286_real_mode_verification_table.py`.",
        "",
        f"- Files: `{summary['total_files']}`",
        f"- Cases: `{summary['total_cases']}`",
        f"- Passed: `{summary['passed_cases']}`",
        f"- Failed: `{summary['failed_cases']}`",
        f"- Skipped: `{summary['skipped_cases']}`",
        "",
        "| Opcode | Sample instruction | Total | Passed | Failed | Skipped | Pass % |",
        "| --- | --- | ---: | ---: | ---: | ---: | ---: |",
    ]

    for item in summary["files"]:
        total = item["total"] or 1
        pass_pct = (item["passed"] * 100.0) / total
        lines.append(
            f"| `{item['opcode']}` | {item['sample_name']} | {item['total']} | {item['passed']} | "
            f"{item['failed']} | {item['skipped']} | {pass_pct:.1f}% |"
        )

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- This table is generated from the JSON summary emitted by `scripts/verify_80286_real_mode.py`.",
            "- The current verifier compares the architectural final register subset and final RAM bytes captured in the hardware dump.",
            "- Cycle-by-cycle verification is intentionally left for a later pass.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a markdown table from 80286 real-mode verification JSON.")
    parser.add_argument("summary_json", type=Path, help="JSON output from verify_80286_real_mode.py")
    parser.add_argument("--output", type=Path, required=True, help="Markdown output path")
    args = parser.parse_args()

    summary = json.loads(args.summary_json.read_text())
    args.output.write_text(render(summary))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
