#!/usr/bin/env python3

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CoverageRow:
    mnemonic: str
    lifter: str
    simulator: str
    tests: str
    notes: str = ""


REAL_MODE_ROWS: tuple[CoverageRow, ...] = (
    CoverageRow("bound", "no", "no", "none", "Still missing."),
    CoverageRow("enter", "yes", "yes", "smoke+runtime", "Level-0 and nested real-mode frame setup now execute."),
    CoverageRow("ins", "yes", "yes", "runtime", "Byte and word forms covered; repeat-aware path exists."),
    CoverageRow("leave", "yes", "yes", "runtime", "Direct execution coverage for stack-frame teardown."),
    CoverageRow("outs", "yes", "yes", "runtime", "Byte and word forms covered; repeat-aware path exists."),
    CoverageRow("popa", "yes", "yes", "runtime", "Direct execution coverage now checks discarded saved-SP semantics."),
    CoverageRow("pusha", "yes", "yes", "runtime", "Direct execution coverage checks original-SP push order."),
)


OUT_OF_SCOPE_ROWS: tuple[tuple[str, str], ...] = (
    ("arpl", "Protected-mode selector privilege instruction; not part of the current real-mode target."),
    ("clts", "Protected-mode/system instruction; not part of the current real-mode target."),
    ("lar", "Protected-mode descriptor-table instruction; not part of the current real-mode target."),
    ("lmsw", "System/CR0 instruction; not part of the current real-mode target."),
    ("lsl", "Protected-mode descriptor-table instruction; not part of the current real-mode target."),
    ("sldt", "Protected-mode/system instruction; not part of the current real-mode target."),
    ("smsw", "System/CR0 instruction; not part of the current real-mode target."),
    ("str", "Protected-mode/system instruction; not part of the current real-mode target."),
    ("verr", "Protected-mode selector-verification instruction; not part of the current real-mode target."),
    ("verw", "Protected-mode selector-verification instruction; not part of the current real-mode target."),
)


def render_markdown() -> str:
    supported = sum(1 for row in REAL_MODE_ROWS if row.lifter == "yes")
    unsupported = sum(1 for row in REAL_MODE_ROWS if row.lifter == "no")

    lines = [
        "# x86-16 80286 Real-Mode Coverage",
        "",
        "Generated by `scripts/build_x86_16_80286_real_mode_coverage.py`.",
        "",
        "This board is intentionally narrower than the main mnemonic matrix.",
        "It tracks the 80286-era mnemonics that are relevant to the current real-mode support goal, plus the protected-mode/system-only mnemonics that are explicitly out of scope for now.",
        "",
        f"- Real-mode rows tracked here: `{len(REAL_MODE_ROWS)}`",
        f"- Lifter `yes`: `{supported}`",
        f"- Lifter `no`: `{unsupported}`",
        "",
        "| Mnemonic | Real-Mode Usable | Lifter | Simulator | Focused tests | Notes |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for row in REAL_MODE_ROWS:
        lines.append(
            f"| `{row.mnemonic}` | yes | {row.lifter} | {row.simulator} | {row.tests} | {row.notes or '-'} |"
        )

    lines.extend(
        [
            "",
            "## Out Of Scope For Now",
            "",
            "| Mnemonic | Why not on the real-mode backlog |",
            "| --- | --- |",
        ]
    )
    for mnemonic, reason in OUT_OF_SCOPE_ROWS:
        lines.append(f"| `{mnemonic}` | {reason} |")

    lines.extend(
        [
            "",
            "## Notes",
            "",
            "- This board is meant to complement, not replace, `docs/x86_16_mnemonic_coverage.md`.",
            "- `Focused tests` summarizes explicit smoke/compare/runtime coverage, not the full corpus-derived surface.",
            "- For this board, `runtime` means direct execution tests in `tests/test_x86_16_compare_semantics.py` against the 16-bit simulator path.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    output = Path(__file__).resolve().parents[1] / "docs" / "x86_16_80286_real_mode_coverage.md"
    output.write_text(render_markdown())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
