#!/usr/bin/env python3

from __future__ import annotations

import argparse
import importlib.util
import sys
from dataclasses import dataclass
from pathlib import Path
from types import ModuleType


SCRIPT_DIR = Path(__file__).resolve().parent
COVERAGE_SCRIPT = SCRIPT_DIR / "build_x86_16_mnemonic_coverage.py"


@dataclass(frozen=True)
class ReferenceHits:
    dosbox: bool
    box86: bool


TRICKY_ROWS = {
    "aaa",
    "aad",
    "aam",
    "aas",
    "bound",
    "cmps",
    "daa",
    "das",
    "div",
    "idiv",
    "imul",
    "ins",
    "into",
    "lods",
    "movs",
    "mul",
    "outs",
    "rcl",
    "rcr",
    "rep",
    "rol",
    "ror",
    "sal",
    "sar",
    "scas",
    "shr",
    "stos",
    "xlat",
}


EXTRA_PATTERNS: dict[str, tuple[str, ...]] = {
    "bound": ("opBOUND", "/* BOUND */"),
    "call": ("lcall", "opCALL", "/* CALL ", "/* CALL FAR"),
    "cmps": ("CMPSB", "CMPSW", "R_CMPSB", "R_CMPSW", "opCMPSB", "opCMPSW"),
    "div": ("/* DIV */", "opDIV", "DIVW", "DIVB"),
    "idiv": ("/* IDIV */", "opIDIV", "IDIVW", "IDIVB"),
    "imul": ("/* IMUL */", "opIMUL", "IMULW", "IMULB"),
    "ins": ("/* INS", "R_INSB", "R_INSW", "opINS"),
    "int": ("/* INT", "opINT", "opINT3"),
    "into": ("/* INTO */", "INTO"),
    "iret": ("/* IRET */", "opIRET"),
    "jmp": ("ljmp", "opJMP", "/* JMP ", "/* JMP FAR"),
    "lods": ("LODSB", "LODSW", "R_LODSB", "R_LODSW", "opLODSB", "opLODSW"),
    "movs": ("MOVSB", "MOVSW", "R_MOVSB", "R_MOVSW", "opMOVSB", "opMOVSW"),
    "mul": ("/* MUL */", "opMUL", "MULW", "MULB"),
    "outs": ("/* OUTS", "R_OUTSB", "R_OUTSW", "opOUTS"),
    "rep": ("REPZ", "REPNZ", "REPE", "REPNE", "DO_PREFIX_REP", "x86_opcodes_REPE", "x86_opcodes_REPNE"),
    "ret": ("RETN", "RETF", "/* RET", "opRET"),
    "rcl": ("RCL", "opRCL"),
    "rcr": ("RCR", "opRCR"),
    "rol": ("ROL", "opROL"),
    "ror": ("ROR", "opROR"),
    "sal": ("SHL", "SAL", "opSHL"),
    "sar": ("SAR", "opSAR"),
    "scas": ("SCASB", "SCASW", "R_SCASB", "R_SCASW", "opSCASB", "opSCASW"),
    "shr": ("SHR", "opSHR"),
    "stos": ("STOSB", "STOSW", "R_STOSB", "R_STOSW", "opSTOSB", "opSTOSW"),
    "wait": ("/* WAIT */",),
    "xlat": ("/* XLAT */", "XLAT"),
}


def load_coverage_module() -> ModuleType:
    spec = importlib.util.spec_from_file_location("x16_cov", COVERAGE_SCRIPT)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"Failed to load coverage script from {COVERAGE_SCRIPT}")
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def normalize_patterns(row) -> tuple[str, ...]:
    patterns = {row.mnemonic.upper(), *(alias.upper() for alias in row.aliases)}
    patterns.update(EXTRA_PATTERNS.get(row.mnemonic, ()))
    return tuple(sorted(patterns))


def collect_reference_text(root: Path) -> str:
    parts: list[str] = []
    for path in sorted(root.rglob("*")):
        if path.is_file() and path.suffix in {".c", ".h"}:
            parts.append(path.read_text(errors="ignore"))
    return "\n".join(parts).upper()


def has_reference_hit(text: str, row) -> bool:
    return any(pattern in text for pattern in normalize_patterns(row))


def reference_hits(dosbox_text: str, box86_text: str, row) -> ReferenceHits:
    return ReferenceHits(
        dosbox=has_reference_hit(dosbox_text, row),
        box86=has_reference_hit(box86_text, row),
    )


def priority_for_row(row, hits: ReferenceHits) -> str:
    if not (hits.dosbox or hits.box86):
        return "low"
    if row.lifter != "yes" or row.simulator != "yes":
        return "high"
    if row.tests == "none":
        return "high"
    if row.mnemonic in TRICKY_ROWS and "compare" not in row.tests:
        return "high"
    if row.mnemonic in TRICKY_ROWS:
        return "medium"
    if row.tests in {"smoke", "runtime", "corpus"}:
        return "medium"
    return "low"


def render_markdown(cod_dir: Path, dosbox_dir: Path, box86_dir: Path) -> str:
    coverage = load_coverage_module()
    rows = coverage.ROWS
    counts = coverage.collect_mnemonics(cod_dir)
    dosbox_text = collect_reference_text(dosbox_dir)
    box86_text = collect_reference_text(box86_dir)

    scored = []
    for row in rows:
        hits = reference_hits(dosbox_text, box86_text, row)
        priority = priority_for_row(row, hits)
        scored.append((priority, coverage.corpus_count(row, counts), row, hits))

    priority_rank = {"high": 0, "medium": 1, "low": 2}
    scored.sort(key=lambda item: (priority_rank[item[0]], -item[1], item[2].mnemonic))

    high = sum(1 for item in scored if item[0] == "high")
    medium = sum(1 for item in scored if item[0] == "medium")
    low = sum(1 for item in scored if item[0] == "low")

    lines = [
        "# x86-16 Reference Priority",
        "",
        "Generated by `scripts/build_x86_16_reference_priority.py`.",
        "",
        "This report uses DOSBox and 86Box as secondary semantic references for triage.",
        "The 80286 dump suite remains the source of truth for final verification.",
        "",
        f"- High-priority rows: `{high}`",
        f"- Medium-priority rows: `{medium}`",
        f"- Low-priority rows: `{low}`",
        "",
        "Priority meanings:",
        "- `high`: present in DOSBox/86Box and still missing strong instruction-level checking or support is partial",
        "- `medium`: present in DOSBox/86Box and already covered somewhat, but still in a historically tricky family",
        "- `low`: either already strongly covered or not a current reference-driven priority",
        "",
        "| Priority | Mnemonic | COD count | Lifter | Simulator | Focused tests | DOSBox | 86Box | Why recheck |",
        "| --- | --- | ---: | --- | --- | --- | --- | --- | --- |",
    ]

    for priority, cod_count, row, hits in scored:
        why = []
        if row.lifter != "yes" or row.simulator != "yes":
            why.append("support gap")
        if row.tests == "none":
            why.append("no focused regression")
        elif row.tests in {"smoke", "runtime", "corpus"}:
            why.append("not compare-backed")
        if row.mnemonic in TRICKY_ROWS:
            why.append("tricky semantics")
        if not why:
            why.append("reference cross-check only")

        lines.append(
            f"| {priority} | `{row.mnemonic}` | {cod_count} | {row.lifter} | {row.simulator} | {row.tests} | "
            f"{'yes' if hits.dosbox else 'no'} | {'yes' if hits.box86 else 'no'} | {', '.join(why)} |"
        )

    lines.extend(
        [
            "",
            "## Workflow",
            "",
            "- Use this table to choose which instructions deserve another hardware-backed pass.",
            "- Treat DOSBox and 86Box as good semantic references for implementation shape and bug-hunting.",
            "- Treat the 80286 `.MOO` dumps as the final oracle when deciding whether behavior is correct.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a DOSBox/86Box reference-priority table for x86-16 mnemonics.")
    parser.add_argument("cod_dir", type=Path, help="Directory containing .COD files")
    parser.add_argument("--dosbox-dir", type=Path, default=Path("/home/xor/inertia_player/libdosbox/src/cpu"))
    parser.add_argument("--86box-dir", dest="box86_dir", type=Path, default=Path("/home/xor/vextest/86Box/src/cpu"))
    parser.add_argument("--output", type=Path, default=None)
    args = parser.parse_args()

    markdown = render_markdown(args.cod_dir, args.dosbox_dir, args.box86_dir)
    if args.output is None:
        print(markdown, end="")
    else:
        args.output.write_text(markdown)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
